name: deploy ke server
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: deploy ke server
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.HOST_FAREISA_SERVER }}
                port: ${{ secrets.PORT_FAREISA_SERVER }}
                username: ${{ secrets.FAREISA_USERNAME }}
                key: ${{ secrets.FAREISA_SYTES_NET }}
                script: |
                    cd /var/www/html/faris/
                    git pull origin main -r
                    git commit -m "tes"
                
            
